name: implement_clean_code_for_store
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.2.0
  dio: ^5.9.0
  equatable: ^2.0.0
  dartz: ^0.10.1
  pretty_dio_logger: ^1.4.0
  animated_snack_bar: ^0.4.0
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  flutter_secure_storage: ^9.2.4
  lottie: ^3.3.1
  easy_localization: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/
     - assets/json/
     - assets/translations/
  #   - images/a_dot_ham.jpeg



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
